[project]
name = "anzagaza"
version = "0.1.0"
dependencies = [
    "Flask==3.0.0",
    "pandas>=2.1.3",
    "requests>=2.32.0",
    "gunicorn==21.2.0",
    "numpy>=1.26.2,<2.3.0",
    "python-dotenv==1.0.0",
]